# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5190e680f3ffd57d4fa8664f07e7dc83"
name = "scan2ship"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/update" ]
  uri = "/webhooks/fulfillments/update"

[access_scopes]
# Scopes for shipping aggregator functionality
# read_orders: Required for ORDERS_CREATE webhook
# write_shipping: To register Carrier Service via GraphQL
# read_fulfillments, write_fulfillments: For fulfillment sync
# write_third_party_fulfillment_orders: For fulfillment flow
# read_locations: For location-based shipping
scopes = "read_orders,write_shipping,read_fulfillments,write_fulfillments,write_third_party_fulfillment_orders,read_locations"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
