# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aa65883dfa2c16395a5d5add65273709"
name = "scan2ship"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_locations,read_orders,write_fulfillments,write_shipping,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
